### PR TITLE
Fix for crash when the pppos interface is restarted

### LINKED ISSUE #20: Core Dump after failing to get IP address on "latest"
**Platform: ESP32**

**Issue:**

If the PPPoS session fails to get an IP address. [This](https://github.com/mongoose-os-libs/pppos/blob/master/src/mgos_pppos.c#L835) line forces the PPPoS stack to reinit. After reaching the same state it finally core dumps twice (not leaving a coredump file behind) and reboots.

**How to reproduce:**

Hook up a modem to the ESP32. I used no flow control lines, TX and RX connected to the ESP32. I'm using UART 2 for this.

Set up the APN settings **incorrectly**. Make sure the modem is on before restarting the firmware.

The stack will reach the part where the PPP link is established, and due to the wrong APN settings it will fail to get an IP address. Afterwards the firmware will restart the PPP stack and fail to get the IP address and the firmware will crash.

**More Info**

The following logs have been acquired running `latest` on both multicore and unicore. Because there are no core dump files, I symbolized the backtraces and placed them at the end of the logs.

[Unicore](https://pastebin.com/k1HVaheD)

[Multicore](https://pastebin.com/G9jMz1NS)

Running on `2.17.0` with the `2.17.0` version of the PPPoS library does not make the firmware crash. After awhile of the PPP link staying in `connected` a `Error 9 (phase 0), reconnect` error is shown and the process is restarted.

**However, I did build the latest PPPoS library on 2.17.0 (release) mOS, compiling the sources directly and can confirm the crash happens as well, leaving the device for some reason on a unrecoverable state where the bootloader is unable to boot mOS again until a hard reset**

Some remote network conditions mean that the PPPoS link might not be able to get an IP address the first time around, so this could affect many devices of ours deployed on the field.

### PR DESCRIPTION
**Pull request by DrBomb**
Fixes #20
- Added PPPOS_CLOSING
- PPPOS_CLOSING starts polling again
- PPPOS_CLOSING still feeds UART info to stack
- Added reconnect flag to jump to PPPOS_INIT after interface is closed
- Modified disconnect state to point to PPPOS_CLOSING

### CODE REVIEW

**Comment by rojer** [comment]
looks good!
please adjust style (braces, indent) and format with clang-format and it's good to go.

**Comment by DrBomb** [comment]
I've added the braces and did a clang-format-8. It didn't change much. I hope it was correctly applied

File: src/mgos_pppos.c [hunk 1]
```diff
@@ -57,6 +57,7 @@ enum mgos_pppos_state {
   PPPOS_CMD_RESP = 9,
   PPPOS_START_PPP = 10,
   PPPOS_RUN = 11,
+  PPPOS_CLOSING = 13
```
Comment (rojer) [inline src/mgos_pppos.c]: please add comma at the end

File: src/mgos_pppos.c [hunk 2]
```diff
@@ -198,6 +201,13 @@ static void mgos_pppos_status_cb(ppp_pcb *pcb, int err_code, void *arg) {
     case PPPERR_USER: {
       /* User (us) called close, do not retry. */
       ppp_free(pcb);
+      /* if reconnect is set, go to INIT. Otherwise go to IDLE */
+      if (pd->reconnect) {
```
Comment (rojer) [inline src/mgos_pppos.c]: mgos_pppos_set_state(pd, (pd->reconnect ? PPPOS_INIT : PPPOS_IDLE));

File: src/mgos_pppos.c [hunk 3]
```diff
@@ -941,13 +964,13 @@ bool mgos_pppos_disconnect(int if_instance) {
...
       pppapi_close(pppcb, 0 /* no_carrier */);
     }
-    pd->cmd_error_state = PPPOS_IDLE;
-    pd->cmd_success_state = PPPOS_IDLE;
-    // If we are not running a user command, go to IDLE immediately,
+    pd->cmd_error_state = PPPOS_CLOSING;
+    pd->cmd_success_state = PPPOS_CLOSING;
+    // If we are not running a user command, go to CLOSING immediately,
     // otherwise finish the command sequence.
     if (pd->state == PPPOS_INIT || pd->state == PPPOS_START_PPP ||
```
Comment (rojer) [inline src/mgos_pppos.c:994]: actually, this needs an update.please add a switch statement with cases for each existing state:

PPPOS_IDLE -> no change
  PPPOS_INIT -> IDLE
  PPPOS_START_SEQ -> IDLE
  PPPOS_RESET -> IDLE
  PPPOS_RESET_HOLD -> IDLE
  PPPOS_RESET_WAIT -> IDLE
  PPPOS_BEGIN_WAIT -> IDLE
  PPPOS_BEGIN -> IDLE
  PPPOS_SETUP -> IDLE
  PPPOS_CMD -> IDLE/CLOSING
  PPPOS_CMD_RESP -> IDLE/CLOSING
  PPPOS_START_PPP -> IDLE/CLOSING
  PPPOS_RUN -> IDLE/CLOSING
  PPPOS_CLOSING - no change

IDLE/CLOSING: go to CLOSING if pppapi_close was invoked (and we expect a callback), otherwise IDLE.

**Review by rojer — CHANGES_REQUESTED** [review]

File: src/mgos_pppos.c (hunk 1 above)
Comment (DrBomb) [reply src/mgos_pppos.c]: Added

File: src/mgos_pppos.c (hunk 2 above)
Comment (DrBomb) [reply src/mgos_pppos.c]: Changed

File: src/mgos_pppos.c (hunk 3 above)
Comment (DrBomb) [reply src/mgos_pppos.c:994]: This is for `pd->cmd_error_state` and `pd->cmd_success_state`? Just to make sure

**Comment by DrBomb** [comment]
Added changes requested @rojer

**Comment by rojer** [comment]
ok, looks good
